log:
  level: INFO

entryPoints:
  web:
    address: :8000

http:
  routers:
    web-secure:
      rule: "PathPrefix(`/`)"
      service: web

  services:
    web:
      loadBalancer:
        servers:
          - url: "http://web:5000"

providers:
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true
