services:
  cookiecutter:
    build:
      context: .
      target: app
    depends_on:
      - docker
    command: gunicorn "app:app" -b 0.0.0.0:5000 -w 4
    environment:
      DOCKER_HOST: tcp://docker:2375
    volumes:
      - data:/data
    env_file:
      - .env

  docker:
    image: docker:dind
    privileged: true
    entrypoint: dockerd --host tcp://0.0.0.0:2375
    volumes:
      - data:/data

  cookiecutter-build:
    build:
      context: .
      target: cookiecutter_builder
    volumes:
      - ./Dockerfile:/data/Dockerfile
    command: wait-for-it docker:2375 -t 30 -s -- docker --host=tcp://docker:2375 build /data -t python3.12_cookiecutter --target cookiecutter
    depends_on:
      - docker

  traefik:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/traefik/production/traefik.yaml:/etc/traefik/traefik.yaml
      - traefik:/etc/traefik/acme/

volumes:
  data: {}
  traefik: {}
