log:
  level: INFO

entryPoints:
  web:
    address: :80

  web-secure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: "hello@srccast.de"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure:
      rule: "Host(`django-cookiecutter.srccast.com`)"
      service: web
      tls:
        certResolver: letsencrypt

  services:
    web:
      loadBalancer:
        servers:
          - url: "http://web:5000"


providers:
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true
